/*
  FlowsInView.java

  Copyright (C) 2010  Rice University

  This software is free software; you can redistribute it and/or
  modify it under the terms of the GNU Lesser General Public
  License as published by the Free Software Foundation; either
  version 2.1 of the License, or (at your option) any later version.

  This software is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General Public
  License along with this software; if not, write to the Free Software
  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
*/

package views.openflow;

import java.util.ArrayList;

import drivers.Driver;
import views.View;
import events.Event;
import events.openflow.PacketInEvent;

/**
 * Contains all FlowIn events generated by the LocationManagementApp
 * @author Zheng Cai
 */
public class FlowsInView extends View {
    public static class FlowIn {
	public PacketInEvent pi;
	public RegisteredHostsView.Location dst;
		
	public FlowIn(PacketInEvent p, RegisteredHostsView.Location d) {
	    pi =  p;
	    dst = d;
	}
    }
	
    public ArrayList<FlowIn> queue;
	
    public FlowsInView() {
	queue = new ArrayList<FlowIn>();
    }

    @Override
	public void commit(Driver driver) {

    }

    @Override
	public boolean processEvent(Event e) {
	return false;
    }

    @Override
	public boolean whetherInterested(Event e) {
	return false;
    }

    @Override
	public void print() {

    }
}
